import { Camera, CameraProvider } from "@/lib/providers/types";

const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60 * 1000).toISOString();

const buildPreview = (id: string) => `/api/mock-image/${id}`;

const mockCameras: Camera[] = [
  {
    id: "hk-central-harbor-01",
    name: "Central Ferry Piers",
    country: "Hong Kong",
    city: "Hong Kong",
    category: "harbor",
    provider: "Hong Kong Transport Department",
    latitude: 22.2877,
    longitude: 114.1588,
    previewImageUrl: buildPreview("hk-central-harbor-01"),
    officialSourceUrl: "https://www.td.gov.hk/en/transport_in_hong_kong/its/road_traffic_information/index.html",
    lastUpdated: minutesAgo(2),
    refreshSeconds: 60,
    tags: ["harbor", "downtown", "night view"],
    status: "online",
    licenseNote: "Mocked from a public-provider schema for UI development. Verify Hong Kong Transport Department reuse terms before production.",
    description: "Harbor-side public traffic camera overlooking the Central waterfront and ferry approach lanes.",
  },
  {
    id: "hk-kowloon-bridge-01",
    name: "Cross-Harbor Tunnel North Portal",
    country: "Hong Kong",
    city: "Kowloon",
    category: "bridge",
    provider: "Hong Kong Transport Department",
    latitude: 22.3033,
    longitude: 114.1797,
    previewImageUrl: buildPreview("hk-kowloon-bridge-01"),
    officialSourceUrl: "https://www.td.gov.hk/en/transport_in_hong_kong/its/road_traffic_information/index.html",
    lastUpdated: minutesAgo(6),
    refreshSeconds: 90,
    tags: ["bridge", "rush hour", "harbor"],
    status: "online",
    licenseNote: "Mocked from a public-provider schema for UI development. Verify provider terms before launch.",
    description: "Major crossing approach that typically spikes during evening commuter traffic.",
  },
  {
    id: "sg-marina-bay-01",
    name: "Marina Coastal Expressway",
    country: "Singapore",
    city: "Singapore",
    category: "highway",
    provider: "Singapore Land Transport Authority",
    latitude: 1.2824,
    longitude: 103.8586,
    previewImageUrl: buildPreview("sg-marina-bay-01"),
    streamUrl: "/mock-stream/sg-marina-bay-01",
    officialSourceUrl: "https://datamall.lta.gov.sg/content/datamall/en.html",
    lastUpdated: minutesAgo(3),
    refreshSeconds: 60,
    tags: ["rush hour", "downtown", "night view"],
    status: "online",
    licenseNote: "Mocked from the LTA public-data contract. Validate image and attribution rules before production.",
    description: "Expressway segment near Marina Bay with a strong downtown skyline backdrop.",
  },
  {
    id: "sg-woodlands-border-01",
    name: "Woodlands Checkpoint Northbound",
    country: "Singapore",
    city: "Singapore",
    category: "border crossing",
    provider: "Singapore Land Transport Authority",
    latitude: 1.4451,
    longitude: 103.7697,
    previewImageUrl: buildPreview("sg-woodlands-border-01"),
    officialSourceUrl: "https://datamall.lta.gov.sg/content/datamall/en.html",
    lastUpdated: minutesAgo(5),
    refreshSeconds: 60,
    tags: ["border crossing", "traffic", "rush hour"],
    status: "online",
    licenseNote: "Mocked from the LTA public-data contract. Validate image and attribution rules before production.",
    description: "Checkpoint approach camera used for monitoring border queue conditions.",
  },
  {
    id: "fi-helsinki-rail-01",
    name: "Helsinki Central Rail Yard",
    country: "Finland",
    city: "Helsinki",
    category: "rail",
    provider: "Finnish Transport Infrastructure Agency",
    latitude: 60.1719,
    longitude: 24.9414,
    previewImageUrl: buildPreview("fi-helsinki-rail-01"),
    officialSourceUrl: "https://www.digitraffic.fi/en/",
    lastUpdated: minutesAgo(9),
    refreshSeconds: 120,
    tags: ["rail", "snow", "downtown"],
    status: "stale",
    licenseNote: "Mocked from an open transport-data schema. Confirm latest Digitraffic licensing details before production.",
    description: "Rail operations view from central Helsinki with weather shifts visible across the tracks.",
  },
  {
    id: "fi-tampere-highway-01",
    name: "Tampere Ring Road",
    country: "Finland",
    city: "Tampere",
    category: "highway",
    provider: "Finnish Transport Infrastructure Agency",
    latitude: 61.4982,
    longitude: 23.761,
    previewImageUrl: buildPreview("fi-tampere-highway-01"),
    officialSourceUrl: "https://www.digitraffic.fi/en/",
    lastUpdated: minutesAgo(4),
    refreshSeconds: 120,
    tags: ["snow", "highway", "mountain"],
    status: "online",
    licenseNote: "Mocked from an open transport-data schema. Confirm latest Digitraffic licensing details before production.",
    description: "High-latitude road camera tuned for visibility and winter-condition checks.",
  },
  {
    id: "us-seattle-waterfront-01",
    name: "Seattle Waterfront Traffic",
    country: "United States",
    city: "Seattle",
    category: "harbor",
    provider: "Seattle Department of Transportation",
    latitude: 47.6075,
    longitude: -122.3425,
    previewImageUrl: buildPreview("us-seattle-waterfront-01"),
    officialSourceUrl: "https://web.seattle.gov/Travelers/",
    lastUpdated: minutesAgo(2),
    refreshSeconds: 45,
    tags: ["harbor", "bridge", "downtown"],
    status: "online",
    licenseNote: "Mocked using a public municipal camera shape. Review Seattle data access terms before production.",
    description: "Waterfront corridor camera with ferry traffic and port access routes.",
  },
  {
    id: "us-newyork-downtown-01",
    name: "Lower Manhattan Broadway",
    country: "United States",
    city: "New York",
    category: "downtown",
    provider: "NYC Department of Transportation",
    latitude: 40.7104,
    longitude: -74.0087,
    previewImageUrl: buildPreview("us-newyork-downtown-01"),
    streamUrl: "/mock-stream/us-newyork-downtown-01",
    officialSourceUrl: "https://webcams.nyctmc.org/",
    lastUpdated: minutesAgo(1),
    refreshSeconds: 60,
    tags: ["downtown", "rush hour", "night view"],
    status: "online",
    licenseNote: "Mocked from a public municipal camera shape. Confirm NYC DOT terms before production.",
    description: "Dense downtown street view used for traffic observation in the financial district.",
  },
  {
    id: "us-sanfrancisco-bridge-01",
    name: "Bay Bridge East Approach",
    country: "United States",
    city: "San Francisco",
    category: "bridge",
    provider: "California Department of Transportation",
    latitude: 37.7983,
    longitude: -122.3778,
    previewImageUrl: buildPreview("us-sanfrancisco-bridge-01"),
    officialSourceUrl: "https://cwwp2.dot.ca.gov/vm/streamlist.htm",
    lastUpdated: minutesAgo(8),
    refreshSeconds: 75,
    tags: ["bridge", "harbor", "rush hour"],
    status: "stale",
    licenseNote: "Mocked from a public state camera structure. Verify Caltrans terms before production.",
    description: "Bridge corridor view capturing the eastbound merge and bay haze conditions.",
  },
  {
    id: "jp-tokyo-rail-01",
    name: "Tokyo Station East Gates",
    country: "Japan",
    city: "Tokyo",
    category: "rail",
    provider: "Tokyo Metropolitan Government",
    latitude: 35.6814,
    longitude: 139.767,
    previewImageUrl: buildPreview("jp-tokyo-rail-01"),
    officialSourceUrl: "https://www.kotsu.metro.tokyo.jp/eng/",
    lastUpdated: minutesAgo(11),
    refreshSeconds: 90,
    tags: ["rail", "downtown", "rush hour"],
    status: "stale",
    licenseNote: "Mocked from a public transit-camera pattern. Confirm operator terms before production.",
    description: "Station-area public camera with commuter density and roadway flow in one frame.",
  },
  {
    id: "jp-osaka-downtown-01",
    name: "Dotonbori Riverwalk",
    country: "Japan",
    city: "Osaka",
    category: "downtown",
    provider: "Osaka Prefecture Public Works",
    latitude: 34.6687,
    longitude: 135.503,
    previewImageUrl: buildPreview("jp-osaka-downtown-01"),
    officialSourceUrl: "https://www.pref.osaka.lg.jp/",
    lastUpdated: minutesAgo(7),
    refreshSeconds: 120,
    tags: ["downtown", "night view", "harbor"],
    status: "online",
    licenseNote: "Mocked from a public prefecture camera pattern. Confirm provider terms before production.",
    description: "Urban riverwalk scene with late-night foot traffic and nearby arterial roads.",
  },
  {
    id: "au-sydney-beach-01",
    name: "Bondi Beach Surf Cam",
    country: "Australia",
    city: "Sydney",
    category: "beach",
    provider: "Transport for NSW",
    latitude: -33.8908,
    longitude: 151.2743,
    previewImageUrl: buildPreview("au-sydney-beach-01"),
    streamUrl: "/mock-stream/au-sydney-beach-01",
    officialSourceUrl: "https://www.livetraffic.com/",
    lastUpdated: minutesAgo(3),
    refreshSeconds: 60,
    tags: ["beach", "night view", "weather"],
    status: "online",
    licenseNote: "Mocked from a public traffic-camera schema. Check provider rights and surf-camera reuse permissions before production.",
    description: "Coastal public camera useful for surf, beach crowd, and weather snapshots.",
  },
  {
    id: "au-brisbane-bridge-01",
    name: "Story Bridge Southbound",
    country: "Australia",
    city: "Brisbane",
    category: "bridge",
    provider: "Queensland Department of Transport and Main Roads",
    latitude: -27.4647,
    longitude: 153.0345,
    previewImageUrl: buildPreview("au-brisbane-bridge-01"),
    officialSourceUrl: "https://qldtraffic.qld.gov.au/",
    lastUpdated: minutesAgo(12),
    refreshSeconds: 90,
    tags: ["bridge", "river", "downtown"],
    status: "offline",
    licenseNote: "Mocked from a public state camera structure. Check provider rights before production.",
    description: "Bridge approach camera that occasionally drops out during maintenance windows.",
  },
  {
    id: "de-hamburg-harbor-01",
    name: "Port of Hamburg Container Gates",
    country: "Germany",
    city: "Hamburg",
    category: "harbor",
    provider: "Hamburg Port Authority",
    latitude: 53.5439,
    longitude: 9.9663,
    previewImageUrl: buildPreview("de-hamburg-harbor-01"),
    officialSourceUrl: "https://www.hamburg-port-authority.de/en/",
    lastUpdated: minutesAgo(4),
    refreshSeconds: 90,
    tags: ["harbor", "border crossing", "night view"],
    status: "online",
    licenseNote: "Mocked from a public port-camera schema. Confirm licensing before production.",
    description: "Harbor logistics camera showing truck queues and gate throughput.",
  },
  {
    id: "de-berlin-downtown-01",
    name: "Alexanderplatz Ring",
    country: "Germany",
    city: "Berlin",
    category: "downtown",
    provider: "Berlin Traffic Information Center",
    latitude: 52.5219,
    longitude: 13.4132,
    previewImageUrl: buildPreview("de-berlin-downtown-01"),
    officialSourceUrl: "https://viz.berlin.de/",
    lastUpdated: minutesAgo(6),
    refreshSeconds: 60,
    tags: ["downtown", "rail", "rush hour"],
    status: "online",
    licenseNote: "Mocked from a public city camera structure. Confirm provider terms before production.",
    description: "Dense multimodal downtown node with tram, rail, and vehicle traffic.",
  },
  {
    id: "ca-vancouver-bridge-01",
    name: "Lions Gate North Approach",
    country: "Canada",
    city: "Vancouver",
    category: "bridge",
    provider: "DriveBC",
    latitude: 49.3128,
    longitude: -123.1387,
    previewImageUrl: buildPreview("ca-vancouver-bridge-01"),
    officialSourceUrl: "https://www.drivebc.ca/",
    lastUpdated: minutesAgo(2),
    refreshSeconds: 75,
    tags: ["bridge", "mountain", "harbor"],
    status: "online",
    licenseNote: "Mocked from a provincial traffic-camera schema. Confirm DriveBC usage terms before production.",
    description: "Bridge approach with mountain visibility and harbor traffic in the background.",
  },
  {
    id: "ca-banff-mountain-01",
    name: "Banff East Gate",
    country: "Canada",
    city: "Banff",
    category: "mountain",
    provider: "Alberta 511",
    latitude: 51.178,
    longitude: -115.5708,
    previewImageUrl: buildPreview("ca-banff-mountain-01"),
    officialSourceUrl: "https://511.alberta.ca/",
    lastUpdated: minutesAgo(10),
    refreshSeconds: 120,
    tags: ["mountain", "snow", "border crossing"],
    status: "stale",
    licenseNote: "Mocked from a provincial traffic-camera schema. Confirm Alberta 511 usage terms before production.",
    description: "Mountain pass and park-entry view used for weather and congestion checks.",
  },
  {
    id: "no-oslo-harbor-01",
    name: "Oslofjord Terminal",
    country: "Norway",
    city: "Oslo",
    category: "harbor",
    provider: "Norwegian Public Roads Administration",
    latitude: 59.9074,
    longitude: 10.7522,
    previewImageUrl: buildPreview("no-oslo-harbor-01"),
    officialSourceUrl: "https://www.vegvesen.no/trafikk",
    lastUpdated: minutesAgo(5),
    refreshSeconds: 120,
    tags: ["harbor", "snow", "night view"],
    status: "online",
    licenseNote: "Mocked from a public roads-camera structure. Confirm licensing before production.",
    description: "Harbor terminal access point with winter lighting and ferry traffic.",
  },
  {
    id: "is-reykjavik-weather-01",
    name: "Reykjavik Coast Weather Cam",
    country: "Iceland",
    city: "Reykjavik",
    category: "weather",
    provider: "Icelandic Road and Coastal Administration",
    latitude: 64.1466,
    longitude: -21.9426,
    previewImageUrl: buildPreview("is-reykjavik-weather-01"),
    officialSourceUrl: "https://umferdin.is/en",
    lastUpdated: minutesAgo(4),
    refreshSeconds: 180,
    tags: ["weather", "harbor", "night view"],
    status: "online",
    licenseNote: "Mocked from a public weather-camera structure. Confirm provider terms before production.",
    description: "Coastal weather camera covering visibility, wind, and harbor approach conditions.",
  },
  {
    id: "kr-seoul-downtown-01",
    name: "Seoul City Hall Loop",
    country: "South Korea",
    city: "Seoul",
    category: "downtown",
    provider: "Seoul Transport Operation & Information Service",
    latitude: 37.5663,
    longitude: 126.9779,
    previewImageUrl: buildPreview("kr-seoul-downtown-01"),
    streamUrl: "/mock-stream/kr-seoul-downtown-01",
    officialSourceUrl: "https://topis.seoul.go.kr/",
    lastUpdated: minutesAgo(3),
    refreshSeconds: 60,
    tags: ["downtown", "rush hour", "night view"],
    status: "online",
    licenseNote: "Mocked from a public Seoul traffic-camera pattern. Verify TOPIS terms before production.",
    description: "Downtown Seoul public road camera centered on a high-volume city loop.",
  },
  {
    id: "kr-busan-harbor-01",
    name: "Busan North Port",
    country: "South Korea",
    city: "Busan",
    category: "harbor",
    provider: "Busan Metropolitan City",
    latitude: 35.1145,
    longitude: 129.0403,
    previewImageUrl: buildPreview("kr-busan-harbor-01"),
    officialSourceUrl: "https://www.busan.go.kr/",
    lastUpdated: minutesAgo(14),
    refreshSeconds: 120,
    tags: ["harbor", "bridge", "night view"],
    status: "offline",
    licenseNote: "Mocked from a public municipal camera pattern. Confirm provider terms before production.",
    description: "Port-facing city camera with bridge traffic and container terminal activity.",
  },
  {
    id: "gb-london-rail-01",
    name: "King's Cross Junction",
    country: "United Kingdom",
    city: "London",
    category: "rail",
    provider: "Transport for London",
    latitude: 51.5319,
    longitude: -0.1236,
    previewImageUrl: buildPreview("gb-london-rail-01"),
    streamUrl: "/mock-stream/gb-london-rail-01",
    officialSourceUrl: "https://tfl.gov.uk/traffic/status/",
    lastUpdated: minutesAgo(1),
    refreshSeconds: 45,
    tags: ["rail", "downtown", "rush hour"],
    status: "online",
    licenseNote: "Mocked from a public transit-camera pattern. Confirm TfL usage terms before production.",
    description: "Rail-adjacent road camera near one of London's busiest stations.",
  },
  {
    id: "gb-brighton-beach-01",
    name: "Brighton Seafront",
    country: "United Kingdom",
    city: "Brighton",
    category: "beach",
    provider: "National Highways",
    latitude: 50.8198,
    longitude: -0.1367,
    previewImageUrl: buildPreview("gb-brighton-beach-01"),
    officialSourceUrl: "https://www.trafficengland.com/",
    lastUpdated: minutesAgo(9),
    refreshSeconds: 90,
    tags: ["beach", "weather", "night view"],
    status: "stale",
    licenseNote: "Mocked from a public roads-camera pattern. Confirm provider terms before production.",
    description: "Seafront and coastal access routes with strong weather swings and night reflections.",
  },
  {
    id: "es-barcelona-downtown-01",
    name: "Plaça de Catalunya",
    country: "Spain",
    city: "Barcelona",
    category: "downtown",
    provider: "Ajuntament de Barcelona",
    latitude: 41.387,
    longitude: 2.17,
    previewImageUrl: buildPreview("es-barcelona-downtown-01"),
    officialSourceUrl: "https://opendata-ajuntament.barcelona.cat/",
    lastUpdated: minutesAgo(2),
    refreshSeconds: 60,
    tags: ["downtown", "night view", "rail"],
    status: "online",
    licenseNote: "Mocked from a city open-data camera shape. Confirm reuse terms before production.",
    description: "Downtown plaza camera with multimodal movement and pedestrian density.",
  },
  {
    id: "mx-tijuana-border-01",
    name: "San Ysidro Southbound",
    country: "Mexico",
    city: "Tijuana",
    category: "border crossing",
    provider: "Baja California Mobility Agency",
    latitude: 32.5411,
    longitude: -117.0308,
    previewImageUrl: buildPreview("mx-tijuana-border-01"),
    officialSourceUrl: "https://www.bajacalifornia.gob.mx/",
    lastUpdated: minutesAgo(5),
    refreshSeconds: 120,
    tags: ["border crossing", "rush hour", "downtown"],
    status: "online",
    licenseNote: "Mocked from a public agency camera pattern. Confirm provider terms before production.",
    description: "Cross-border queue camera with live lane patterns and peak congestion periods.",
  },
];

export const mockProvider: CameraProvider = {
  meta: {
    id: "mock",
    name: "OpenCam Atlas Mock Feed",
    enabled: true,
    supportsLiveData: false,
    status: "active",
    note: "Primary development source with realistic normalized camera records and mock preview images.",
  },
  async getCameras() {
    return mockCameras;
  },
};
